#!/bin/sh
# Description: Hello CSEL1 program

# Path
PROG="/opt/main"

case "$1" in
  start)
    echo "Starting Hello CSEL1" # print in the terminal
    $PROG
    ;;
  stop)
    # nothing to do
    ;;
  *)
    echo "Usage: $0 {start|stop}"
    exit 1
    ;;
esac

exit 0